# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/clojure:lein-2.7.1
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run: lein midje
      - run: lein deploy clojars

  publish:
    docker:
      - image: circleci/clojure:lein-2.7.1
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run: lein deploy clojars

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - publish:
          filters:
            branches:
              only: master
          requires:
            - test